// Code generated by codable; DO NOT EDIT.

package adapter

import "unsafe"

func (d Depth) SizeInByte() int {
	return int(unsafe.Sizeof(Depth{}))
}

func (d Depth) Encode(dst []byte) []byte {
	size := d.SizeInByte()
	if cap(dst) < size {
		dst = make([]byte, size)
	} else {
		dst = dst[:size]
	}

	src := unsafe.Slice((*byte)(unsafe.Pointer(&d)), size)
	copy(dst, src)
	return dst
}

func (d Depth) Decode(src []byte) Depth {
	var result Depth
	size := int(unsafe.Sizeof(result))
	dst := unsafe.Slice((*byte)(unsafe.Pointer(&result)), size)
	copy(dst, src)
	return result
}
