// Code generated by codable; DO NOT EDIT.

package adapter

import "unsafe"

func (o OrderIntent) SizeInByte() int {
	return int(unsafe.Sizeof(OrderIntent{}))
}

func (o OrderIntent) Encode(dst []byte) []byte {
	size := o.SizeInByte()
	if cap(dst) < size {
		dst = make([]byte, size)
	} else {
		dst = dst[:size]
	}

	src := unsafe.Slice((*byte)(unsafe.Pointer(&o)), size)
	copy(dst, src)
	return dst
}

func (o OrderIntent) Decode(src []byte) OrderIntent {
	var result OrderIntent
	size := int(unsafe.Sizeof(result))
	dst := unsafe.Slice((*byte)(unsafe.Pointer(&result)), size)
	copy(dst, src)
	return result
}
