// Code generated by codable; DO NOT EDIT.

package adapter

import "unsafe"

func (i IngestRequest) SizeInByte() int {
	return int(unsafe.Sizeof(i))
}

func (i IngestRequest) Encode(dst []byte) []byte {
	size := i.SizeInByte()
	if cap(dst) < size {
		dst = make([]byte, size)
	} else {
		dst = dst[:size]
	}

	src := unsafe.Slice((*byte)(unsafe.Pointer(&i)), size)
	copy(dst, src)
	return dst
}

func (IngestRequest) Decode(src []byte) IngestRequest {
	var result IngestRequest
	size := int(unsafe.Sizeof(result))
	dst := unsafe.Slice((*byte)(unsafe.Pointer(&result)), size)
	copy(dst, src)
	return result
}
