// Code generated by codable; DO NOT EDIT.

package adapter

import "unsafe"

func (o Order) SizeInByte() int {
	return int(unsafe.Sizeof(o))
}

func (o Order) Encode(dst []byte) []byte {
	size := o.SizeInByte()
	if cap(dst) < size {
		dst = make([]byte, size)
	} else {
		dst = dst[:size]
	}

	src := unsafe.Slice((*byte)(unsafe.Pointer(&o)), size)
	copy(dst, src)
	return dst
}

func (Order) Decode(src []byte) Order {
	var result Order
	size := int(unsafe.Sizeof(result))
	dst := unsafe.Slice((*byte)(unsafe.Pointer(&result)), size)
	copy(dst, src)
	return result
}
